### ISSUE TITLE
[minor] infra.ci logs are mentioning an expired datadog API key

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#2804]
### Service

infra.ci.jenkins.io

### Summary

While working on #2803, we saw log messages of level SEVERE about an invalid datadog key:

```
2022-03-01 16:27:49.140+0000 [id=56]	SEVERE	o.d.j.p.d.c.DatadogHttpClient#getInstance: Datadog API Key is not set properly
2022-03-01 16:27:49.643+0000 [id=54]	SEVERE	o.d.j.p.datadog.DatadogUtilities#severe: API key is invalid, please check your config
```

=> To be diagnosed and  fixed but it is not blocking so low priority 

### Tasks

- [x] Create a new API key in datadog (jenkins-plugin-infra.ci)
- [x] Add this API key to sops
- [ ] Setup datadog on infra.ci with JCasc to specify the new API key
- [x] Add to the team calendar a date for the key rotation 1 year later (max)
- [ ] Check if needed for release.ci (in this case: same steps again with its own key)

**Comment by dduportal** [comment]
As caught by @lemeurherve later (in #2914), we have to:

- Create a new API key in datadog (jenkins-plugin-infra.ci)
- Add this API key to sops
- Setup datadog on infra.ci with JCasc to specify the new API key
- Add to the team calendar a date for the key rotation 1 year later (max)
- Check if needed for release.ci (in this case: same steps again with its own key)

**Comment by dduportal** [comment]
The datadog plugin on infra.ci.jenkins.io looks good now as per its logs:

```console
2022-08-05 12:56:39.934+0000 [id=66]    INFO    o.c.j.p.k.pod.retention.Reaper#watchCloud: set up watcher on kubernetes
2022-08-05 12:56:39.936+0000 [id=66]    INFO    o.c.j.p.k.KubernetesLauncher#launch: Agent has already been launched, activating: kubernetes-jobs-kubernetes-management-main-3048-mnjtf-2p0-qqshg
2022-08-05 12:56:40.024+0000 [id=66]    INFO    o.d.j.p.d.c.DatadogAgentClient#reinitializeStatsDClient: Re/Initialize DogStatsD Client: hostname = datadog.datadog.svc.cluster.local, port = 8125
```

Checking configuration in Jenkins'UI and in datadog now, before closing

**Comment by dduportal** [comment]
Metrics are correctly forwarded to datadog. The dashboard named "Jenkins - Overview" is already filled with data: https://jenkins.datadoghq.com/screen/integration/4/jenkins---overview?from_ts=1660037529290&to_ts=1660041129290&live=true 

<img width="1934" alt="Capture d’écran 2022-08-09 à 12 33 23" src="https://user-images.githubusercontent.com/1522731/183627629-9883a09a-4a23-4f03-a154-f393dd5899ac.png">

**Comment by dduportal** [comment]
Closing as it is done. Good job @lemeurherve !

**Comment by dduportal** [comment]
N.B. the datadog chart was locked in "rollback" mode on temp-privatek8s 8 days ago: uninstalling + reinstalling it manually solved the error, and then the metrics started flowing to datadog.
