### ISSUE TITLE
Meta ticket to remove jenkins-wiki-exporter

### ISSUE THREAD

**Issue by halkeye** [jenkins-infra/helpdesk#3059]
### Service(s)

Jenkins Wiki Exporter

### Summary

- [X] Move wiki migration progress to reports
- [x] Update blog posts/docs that link to it - https://github.com/jenkins-infra/jenkins.io/pull/5298
- [x] Remove from kubernetes-management repo
- [x] Delete from kubernetes
- [x] Delete DNS

**Comment by halkeye** [comment]
Thanks to tim, we've now upgraded https://github.com/jenkins-infra/infra-reports to use builder image, and ported the code from wiki exporter to report

Let mark know that its live now:

halkeye: MarkEWaite (Mark Waite): https://reports.jenkins.io/jenkins-plugin-migration.html is that good enough to shut down wiki exporter?
MarkEWaite (Mark Waite): Absolutely! Thanks so much @halkeye!

**Comment by MarkEWaite** [comment]
Thanks @halkeye!  Yes, confirmed that we can shutdown wiki exporter

**Comment by lemeurherve** [comment]
Thanks @timja & @halkeye!

Service removed.

**Comment by dduportal** [comment]
@lemeurherve how did you effectively remove the service from the Kubernetes cluster? Was is using a persistent volume or any leftover resource?

**Comment by lemeurherve** [comment]
I've manually deleted its deployment then its namespace on temp-privatek8s cluster.
There were no PV.

**Comment by dduportal** [comment]
> I've manually deleted its deployment then its namespace on temp-privatek8s cluster. There were no PV.

~temp-privatek8s~ => prodpublick8s right?

https://github.com/lemeurherve/kubernetes-management/commit/d15b8e1d3fd3789a0aebdf1c4a129e9e1863db57#diff-fc99918efc0a3643e4e0bd777cfc907488a47412b9f27c3e13a2cae7591ba569

**Comment by lemeurherve** [comment]
> temp-privatek8s => prodpublick8s right?

Oups, yes prodpublick8s :)

**Comment by halkeye** [comment]
cc @jenkins-infra/plugin-site who also used to get dependancy notifications for this service. Its now fully retired.
