### ISSUE TITLE
AKS: add cluster `publick8s` and migrate `prodpublick8s` public services on it

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3351]
This issue tracks the work for spawning a new "public" AKS cluster for production to replace the former `prodpublick8s`.

Goals:

- Get rid of the network overlap from the current AKS `prodpublick8s`
- Ensure that the cluster is managed as code
- [Support IPv6 for services hosted in this cluster](https://github.com/jenkins-infra/helpdesk/issues/3307) (requires NOT using CNI for this cluster, forbidding us to use Windows node pools)
  - Ref. https://learn.microsoft.com/en-us/azure/aks/configure-kubenet-dual-stack?tabs=azure-cli%2Ckubectl
- Ensure a new "home" for https://github.com/jenkins-infra/helpdesk/issues/2752 in Azure environment

This issue is the "twin" of https://github.com/jenkins-infra/helpdesk/issues/2844 but for public network.

----

Some notes:

- Node pools:
  - No Windows node pool is expected (only used by release.ci.jenkins.io which will be migrated to `privatek8s`)
  - No Highmem node pool is expected (only used by release.ci.jenkins.io which will be migrated to `privatek8s` - Only reference to `highmem` string in the context of Kubernete in https://github.com/search?q=org%3Ajenkins-infra+highmem&type=code is https://github.com/jenkins-infra/release/blob/902df23d5657c074f184d8e08d1d00d7e3e67c95/PodTemplates.d/release-linux.yaml#L44)
  - The current `agentpool` for `prodpublick8s` should have an equivalent (in term of VM size, disk size and autoscaling limits) in the new `privatek8s`
  - A "default system node pool" is expected, like for `privatek8s`, as a good AKS practise (ref. https://learn.microsoft.com/en-us/azure/aks/use-system-pools?tabs=azure-cli and https://learn.microsoft.com/en-us/azure/aks/use-multiple-node-pools)
- The #3306 is NOT needed (we can reach the private-ingress endpoint using the private's VPN network peering to public)
- [ ] We'll have to decide which can of "egress" (attribute `outboundType`) type to use: https://learn.microsoft.com/en-us/azure/aks/egress-outboundtype
- We'll have to ensure that the CSI storage classe are set to retain for the non-default, and that any "custom" CSI classe is installed
- We'll have to install in this cluster the following (usual) side services:
  - [x] datadog
  - [x] certmanager+acme
  - [x] Nginx (private) ingress controller (with an internal load balancer that should be reachable from the peered private network), and should be the default
  - [x] Nginx (public) ingress controller (with a public LB and public IP)
  - [x] Falco (to ensure some policies are enforced on workloads)
- We'll have to migrate the following services from `prodpublick8s` to this cluster:
  - [x] plugin-site (plugins.jenkins.?io)
  - [x] plugin-site-issues
  - [x] reports (reports.jenkins.io)
  - [x] jenkinsio (⚠️ when changing the DNS, we'll have to watch fastly) (origin.jenkins.io)
  - [x] javadoc (javadoc.jenkins.io)
  - [x] accountapp (accounts.jenkins.io)
  - [x] ldap (ldap.jenkins.io with its own public LB)
  - [x] uplink (uplink.jenkins.io)
  - [x] mirrorbits (get.jenkins.io)
  - [x] keycloak
  - [x] incrementals-publisher
  - [x] jenkins-weekly
  - [x] jenkinsisthewayio-redirect
  - [x] artifact-caching-proxy
  - [x] plugin-health-scoring
  - [x] wiki
  - [x] rating 
```[tasklist]
### Tasks
```

**Comment by lemeurherve** [comment]
With this migration we'll be able to close https://github.com/jenkins-infra/helpdesk/issues/3209

**Comment by dduportal** [comment]
Putting on hold: #2844 tracks the migration of release.ci from `prodpublick8s` to `privatek8s`, before proceeding forward here.

**Comment by lemeurherve** [comment]
weekly.jenkins.io migrated:
- https://github.com/jenkins-infra/kubernetes-management/pull/3930
- https://github.com/jenkins-infra/azure-net/pull/67
- https://github.com/jenkins-infra/kubernetes-management/pull/3931

We noticed that while the LDAP wasn't accessible for Jenkins, it doesn't rendered the HTML set as welcome message.

**Comment by dduportal** [comment]
Next steps: migrating the services relying on a postgreSQL database.

To avoid any propagation of the network overlap, we need a flexible Postgres instance that the `public-vnet` network can access.

A new instance has to be created:

- Delegated subnet: https://github.com/jenkins-infra/azure-net/pull/78
- New instance: https://github.com/jenkins-infra/azure/pull/359

Alas, Azure Flexible servers do not support IPv6 virtual nets, so we'll have to find another solution.
Current scenario is to create a dedicated virtual net, IPv4 only, and study the methods to access it privately.

- Rollback: https://github.com/jenkins-infra/azure/pull/359

**Comment by dduportal** [comment]
As per https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-networking:

- A given flexible Postgres instance cannot be in a virtual network and have public endpoint as the same time
- The only way to access a Flexible Postgres instance in a virtual network from another network is to use network peering
- The "private link" concept is only for the DNS resolution

=> as we want a managed database with no public endpoint, it means we need a dedicated vnet + (delegated) subnet for the new Postgres flexbible instance.
Only unknown is the peering behavior with IPv6 / IPv4.

**Comment by dduportal** [comment]
- The `public-db` instance is now working, reachable from both `private` and `public` vnets
- Database for keycloak is now managed in `public-db` by Terraform (and the postgres provider)
- Keycloak migration in progress:
  - Not managed anymore from prodpublick8s (but not removed yet)
  - Issues with Dualstask network mode, should be fixed but no HA available (we did not use it so it's ok)
  - WiP on the VPN routing to allow reaching "private" IPs (such as private-ingress LB) of the `public` network throug the private VPN

**Comment by dduportal** [comment]
Keycloak is migrated with success to the new cluster:

- DNS record
- Network routes (through the VPN)

Removed the former ingress to confirm and looks good for both @smerle33 and I with the private VPN connected


Next step: gotta remove the migrated resources from prodpublick8s to be really sure that nothing runs on the former cluster (starting with keycloak only as it would only iumpact infra team: gotta wait for annoucement for public services)

**Comment by dduportal** [comment]
Update:

Keycloak cleanup:
- Namespace delete from `prodpublick8s` with success
- Database deleted from `public` PgSQL instance with success
- https://admin.accounts.jenkins.io works well


Removed the `jenkins-weekly`, `javadoc`, `jenkinsisthewayio-redirector` and `wiki` namespaces from `prodpublick8s (already migrated)

Removed the (empty) namespace `archives` from `prodpublick8s`


Next candidates: Plugin Helath Score and rating

**Comment by dduportal** [comment]
Migration of plugin-health score done, in mob-programming with the help of @smerle33 and @alecharp 

- Annonce status.jenkins.io - https://github.com/jenkins-infra/status/pull/289
- Opportunity to verify the impact on plugins.jenkins.io when PHS goes down
  - Manually: backup of the ingress in `prodpublick8s`, delete ingress, and check: no impact on plugins.jenkins.io (only on the static generation)
  - Restored the ingress
- Disabled jenkins-infra/kubernetes-management
- Deleted (manually) namespace in `prodpublick8s`
- Backup BDD -> restore to new instance `public-db`
- Migrated Helm release to publick8s - https://github.com/jenkins-infra/kubernetes-management/pull/4000
- Change the cron to validate deployment - https://github.com/jenkins-infra/kubernetes-management/commit/ea7a257612c7143322f52076dba13c55868bdb65
- Enabled jenkins-infra/kubernetes-management => deployment of PHS success
- Checking logs: both cron tasks (Update Center and plugins) went well
- Migrated DNS: https://github.com/jenkins-infra/azure-net/pull/85
  -  => homepage visible at https://plugin-health.jenkins.io/probes after 2-3 minutes
- Rollback cron - https://github.com/jenkins-infra/kubernetes-management/pull/4001
- Deleted the old postgres database from `public` instance
- Closes status - https://github.com/jenkins-infra/status/pull/290
- Check plugins.jenkins.io generation in infra.ci:
  - Triggered a build - https://infra.ci.jenkins.io/job/website-jobs/job/plugin-site/job/master/2989
  - https://plugins.jenkins.io/ui/search/?query=kube works without error
  
✅ 🚀

**Comment by dduportal** [comment]
Update:

- Fixed the updatecli manifest for `plugin-health-score` (we have to do this for each migration): https://github.com/jenkins-infra/kubernetes-management/pull/4003
- Manage (and fix) as code the jenkins-ci.org records for `javadoc` and `wiki`: https://github.com/jenkins-infra/azure-net/pull/86
- Removed the (unused) `grafan` DNS records on both `jenkins.io` and `jenkins-ci.org` domains:

![Capture d’écran 2023-05-26 à 17 49 31](https://github.com/jenkins-infra/helpdesk/assets/1522731/88651a83-819f-4bfb-8a9c-b50f45995b92)
![Capture d’écran 2023-05-26 à 17 50 01](https://github.com/jenkins-infra/helpdesk/assets/1522731/cefc6365-7b61-4811-b6c7-bf948096b8c7)

**Comment by dduportal** [comment]
Plan for the Incremental Publisher migration (https://github.com/jenkins-infra/iep/tree/master/iep-009):

- Open Status
- Send email to developer mailing list
- No database, no persistence: can be migrated without downtime
  - Checked configuration and secrets: no need to update any environment-related element ✅
  - No whitelist.denylist on artifactory ✅
- Migrate Helm release management to publick8s
- Migrate DNS
- Test a PR builds on ci.jenkins.io that should publish with success
- Delete namespace in prodpublick8s
- Test again PR builds on ci.jenkins.io that should publish with success
- Close Status + email

**Comment by dduportal** [comment]
Migration of the Uplink and Rating services

- [x] Open Status (both at same time) - https://github.com/jenkins-infra/status/pull/294
- No need for email on these 2
- Databases:
  - Rating:
    - [ ] Creating database in Terraform Azure
    - [ ] Initial backup/restore to evaluate the amount of time
  - Rating:
    - [ ] Creating database in Terraform Azure
    - [ ] Initial backup/restore to evaluate the amount of time   
- [ ] Prepare to migrate Helm release management to publick8s (both at same time, PR to prepare prior to the operation) - TODO
- Shut down services  on `prodpublick8s` (removing ingresses manually to fail incoming requests)
  - [ ] Backup ingresses
  - [ ] Remove ingresses
- [ ] Deploy on kuberenetes-management
- [ ] Migrate DNS - TODO
- Sanity Checks:
    - [ ]On jenkins.io, test to rate a release
    - [ ]uplink: check the new webpage
- Delete namespaces in prodpublick8s
  - [ ] Rating
  - [ ] Uplink
- [ ] Close Status

**Comment by dduportal** [comment]
Migration of the Uplink service

Main challenge is the database size: 88% storage used of the available 85 Gb for the current PostgreSQL Single Server:

- We need the disk space on the new PostgreSQL flexible server
- The service interruption is constrained by the backup/restore time

Plan:


- Increase current storage server to 120 Gb - TODO
- [ ] Open Status - TODO
- No need for email communication
- Database
  - [x] Creating database in Terraform Azure - https://github.com/jenkins-infra/azure/pull/371
  - [ ] Initial backup/restore to evaluate the amount of time (first test without pg_dump tuning is > 20 min with a need of 75 GTb available disk space)
- [ ] Prepare to migrate Helm release management to publick8s (both at same time, PR to prepare prior to the operation) - TODO
- Shut down service  on `prodpublick8s` (removing ingress manually to fail incoming requests)
  - [ ] Backup ingress
  - [ ] Remove ingress
- Deploy on Kubernetes:
  - [ ] Push the new credentials to jenkins-infra/chart-secrets - <TODO insert commit ref here once done>
  - [ ] Merge the jenkins-infra/kubernetes-management PR
- [ ] Migrate DNS - TODO
- [ ] Sanity Checks: uplink: check the main webpage + sentry
- [ ] Delete namespaces in prodpublick8s
- [ ] Delete former database
- [ ] Close Status

**Comment by dduportal** [comment]
Update:

- https://github.com/jenkins-infra/azure/pull/372 to cleanup resources after rating migration
- https://github.com/jenkins-infra/azure/pull/373 to increase the storage size of the `public-db` instance to sustain the `uplink` database

**Comment by dduportal** [comment]
Update "Uplink":

on the (new.)ci.jenkins.io:
  - Installed postgres-client
  - Checked size of `/var/lib/jenkins/`: 478 Gb available
  - OLD DB: 
    - Connection OK with `psql --host=produplink.postgres.database.azure.com --username='uplinkadmin@produplink' --password uplink`
    - Ran a `VACUUM VERBOSE` in a screen named `uplink_vacuum`
  - NEW DB:
    - Connection OK with `psql --host=public-db.postgres.database.azure.com --username=uplink --password uplink`
  - Backup:
    - Idea is to disable compression, use "directory" (recursive for better I/Os) and all vCPUs
    - `time pg_dump --host=produplink.postgres.database.azure.com --username='uplinkadmin@produplink' --password --dbname=uplink --compress=0 --jobs=8 --format=d --file=/var/lib/jenkins/uplink_$(date +%Y%m%d_%H%M%S)` in a screen named `uplink_dump`

**Comment by dduportal** [comment]
Update in uplink:
- Vacuum went fine but did not decrease the storage size (expected as the event table is huge).
- First successful dump took 523 min and weight 105Gb 
  - Limitation was due to not enough jobs and vacuum competing for resources on server side
- Second try with 64 jobs: the I/O disk write is up from 200 Kb/s to 8 Mb/s, let's hope for a less than 1 hour dump now

**Comment by dduportal** [comment]
Update with `uplink`: as the "old" PostgreSQL is reachabale from the new cluster and has too much data, I've opened https://github.com/jenkins-infra/helpdesk/issues/3609 for the database migration.

Also, it seems that the "old" database is a Postgres 10 instance while our `public-db` is version 13.

Gotta migrate uplink today, keeping the same database as before to avoid too many changes.

**Comment by lemeurherve** [comment]
Migration of uplink.jenkins.io completed.

**Comment by lemeurherve** [comment]
Migration of the Reports service:

- [ ] Open Status - TODO
- [-] No need for email communication
- [-] No database, only a storage account on Azure, accessible to the new cluster
- [ ] Deploy on the new Kubernetes cluster
  - [ ] Migrate Helm release management to publick8s - TODO
  - [ ] Verify the new application is up and running (testing its ingress and checking logs)
- [ ] Migrate DNS - TODO
- [ ] Sanity Checks
- [ ] Delete namespace in prodpublick8s
- [ ] Sanity Checks
- [ ] Close Status - TODO

**Comment by lemeurherve** [comment]
Migration of https://reports.jenkins.io completed.

**Comment by lemeurherve** [comment]
Migration of [accountapp](https://accounts.jenkins.io) service:

- [ ] Open status - TODO
- [-] No need for email communication
- [-] No data migration: stateless service
- [ ] Deploy on the new Kubernetes cluster
  - [ ] Migrate Helm release management to publick8s (and add `nodeSelector`) - TODO
  - [ ] Verify the new application is up and running (testing its ingress and checking logs)
- [ ] Migrate DNS (with `moved` block) - TODO
- [ ] Sanity checks
- [ ] Delete `accountapp` namespace in `prodpublick8s` cluster
- [ ] Sanity checks
- [ ] Close status - TODO

**Comment by lemeurherve** [comment]
Migration of https://accounts.jenkins.io completed, no service interruption.

**Comment by lemeurherve** [comment]
Migration of the LDAP service:

- [ ] Open status - TODO
- [ ] Send email to the developer mailing list 
- [ ] Create a new storage account accessible to the new cluster dedicated to LDIF dumps from LDAP
- [ ] Deploy on the new Kubernetes cluster
  - [ ] Migrate Helm release management to publick8s (and add `nodeSelector`) - TODO
  - [ ] Verify the new application is up and running (testing its ingress and checking logs)
  - [ ] Restore an LDIF dump for testing purpose
  - [ ] Sanity checks
- [ ] Switch accountapp DNS (with `moved` block) from publick8s to status.jenkins.io as we need to stop writes on LDAP while performing the LDIF dump - TODO
- [ ] Dump and retrieve LDIF from prodpublick8s and transfer it to the new storage account
- [ ] Restore the dump in publick8s
- [ ] Sanity checks
- [ ] Migrate LDAP DNS (with `moved` block) from prodpublick8s to status.jenkins.io as we need to stop writes on LDAP while performing the LDIF dump - TODO
- [ ] Delete `ldap` namespace in `prodpublick8s` cluster
- [ ] Sanity checks
- [ ] Switch back accountapp DNS (with `moved` block) from status.jenkins.io to publick8s - TODO
- [ ] Close status - TODO

**Comment by dduportal** [comment]
Update on the LDAP: https://github.com/jenkins-infra/azure/pull/385#issuecomment-1577251779 

=> there are missing elements to allow managing storage accounts in some of the publick8s networks

**Comment by lemeurherve** [comment]
All preliminary steps for the LDAP migration are completed, I'll proceed to the switch tomorrow.

**Comment by lemeurherve** [comment]
Although the intended redirections from [accounts.jenkins.io](http://accounts.jenkins.io/) & [accounts.jenkins-ci.org](http://accounts.jenkins-ci.org/) to [status.jenkins.io](http://status.jenkins.io/) didn’t worked as expected (SAN cert issue?), the LDAP migration has been successfully completed, no service interruption.

**Comment by lemeurherve** [comment]
Migration of mirrorbits (get.jenkins.io,  mirrors.jenkins.io,  mirrors.jenkins-ci.org, fallback.get.jenkins.io) service:

- [ ] Open status - TODO
- [-] No need for email communication
- [-] No data migration: the existing redis database is accessible from `publick8s`
- [ ] Deploy on the new Kubernetes cluster
  - [ ] Migrate Helm release management to `publick8s` (and add `nodeSelector`) - TODO
  - [ ] Verify the new application is up and running (testing its ingress and checking logs)
- [ ] Migrate DNS (with `moved` block)
- [ ] Sanity checks
- [ ] Disable `accountapp` ingress in `prodpublick8s` cluster
- [ ] Sanity checks
- [ ] Delete `accountapp` namespace in `prodpublick8s` cluster
- [ ] Sanity checks
- [ ] Close status - TODO

**Comment by lemeurherve** [comment]
Migration of [plugin-site-issues](https://plugin-site-issues.jenkins.io) service:

- [ ] Open status - TODO
- [-] No need for email communication
- [-] No data migration: stateless service
- [ ] Deploy on the new Kubernetes cluster
  - [ ] Migrate Helm release management to `publick8s` (and add `nodeSelector`) - TODO
  - [ ] Verify the new application is up and running (testing its ingress and checking logs)
- [ ] Migrate DNS (with `moved` block)
- [ ] Sanity checks
- [ ] Disable ingress in `prodpublick8s` cluster
- [ ] Sanity checks
- [ ] Delete `plugin-site-issues` namespace in `prodpublick8s` cluster
- [ ] Sanity checks
- [ ] Close status - TODO

**Comment by lemeurherve** [comment]
Migration of mirrrorbits and plugin-site-issues completed, no service interruption.

As a precaution, we'll delete the `mirrorbits` namespace from `prodpublick8s` tomorrow or Wednesday.

**Comment by lemeurherve** [comment]
Migration of [plugin-site](https://plugins.jenkins.io) service:

- [ ] Open status - TODO
- [-] No need for email communication
- [-] No data migration: stateless service
- [ ] Deploy on the new Kubernetes cluster
  - [ ] Migrate Helm release management to `publick8s` (and add `nodeSelector`) - TODO
  - [ ] Verify the new application is up and running (testing its ingress and checking logs)
- [ ] Migrate DNS plugins.origin.jenkins.io (with `moved` block) - TODO
- [ ] Sanity checks: successfully logged in
- [ ] Disable ingress in `prodpublick8s` cluster
- [ ] Sanity checks
- [ ] Refresh/purge Fastly cache
- [ ] Sanity checks
- [ ] Delete namespace in `prodpublick8s` cluster
- [ ] Close status - TODO

**Comment by lemeurherve** [comment]
Migration of [jenkins.io](https://www.jenkins.io) service:

- [ ] Open status - TODO
- [-] No need for email communication
- [-] No data migration: stateless service
- [ ] Deploy on the new Kubernetes cluster
  - [ ] Migrate Helm release management to `publick8s` (and add `nodeSelector`) - TODO
  - [ ] Verify the new application is up and running (testing its ingress and checking logs)
- [ ] Migrate `www.origin.jenkins.io` (with `moved` block) - TODO
- [ ] Sanity checks: successfully logged in
- [ ] Disable ingress in `prodpublick8s` cluster
- [ ] Sanity checks
- [ ] Refresh/purge Fastly cache
- [ ] Sanity checks
- [ ] Delete namespace in `prodpublick8s` cluster
- [ ] Close status - TODO

**Comment by lemeurherve** [comment]
plugin-site migration completed, no service interruption.

**Comment by lemeurherve** [comment]
# Cleanup of unused DNS records found while working on this issue

## A records pointing to `52.167.253.43` (`prodpublick8s` public IP)
- [ ] public.aks.jenkins.io
- [ ] jenkins-ci.org (apex record), to be imported in terraform and changed to `20.119.232.75` (`publick8s` public IP)

## CNAME records pointing to `publick.aks.jenkins.io` (ie `prodpublick8s` cluster):
- [ ] archives.azure.jenkins.io
- [ ] mirror.azure.jenkins.io
- [ ] polls.jenkins.io
- [ ] beta.accounts.jenkins.io
- [ ] customize.jenkins.io

**Comment by lemeurherve** [comment]
As we've noticed quite many requests still send to `mirrorbits` on `prodpublick8s`, we'll postpone the cluster deletion to next week, and @dduportal will see for the publication of a blogpost indicating the migration of this service to the new cluster.

**Comment by dduportal** [comment]
Namespaces removal: @lemeurherve and I paired and removed the following namespaces from `prodpublick8s`:

- `datadog` (causing https://github.com/jenkins-infra/datadog/pull/193 😅)
- `cert-manager`
- `private-nginx-ingress`.


Remaining namespaces are required until https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1591672053 is fixed.

**Comment by dduportal** [comment]
> As we've noticed quite a lot of remaining requests still send to `mirrorbits` on `prodpublick8s`, we'll postpone the cluster deletion to next week, and @dduportal will see for the publication of a blogpost indicating the migration of this service to the new cluster.

As discussed with the last infrastructure meeting:

- We are planning to decommission the former `prodpublick8s` cluster the Tuesday 27 June 2023, including the former  mirror service and the former IPv4
- Community thread in: https://community.jenkins.io/t/new-public-ipv4-for-jenkins-mirrors/8137
- Jenkins Blog post:
  - PR: <TBD>
  - Direct link: <TBD>

**Comment by dduportal** [comment]
Update:

- Cluster `prodpublick8s` destroyed with its resource group
- https://github.com/jenkins-infra/helpdesk/issues/3639 should be fixed

**Comment by lemeurherve** [comment]
Additional monitors added: https://github.com/jenkins-infra/datadog/pull/195

Potential improvements for later:
- [ ] use a PV/PVC instead of azurefile for plugin-site storage
- [ ] evaluate if plugin-site needs the same GitHub and Jira credentials as plugin-site-api (optional)
- [ ] create an issue for a mechanism to display a maintenance page on services while operating on them
- [ ] activate the "secure transfer required" for javadoc storage account
- [ ] add cluster outbound IPs as terraform output

After 3 years and 27 days of good and faithful service, `prodpublick8s` is not anymore, closing this issue 🤗
