### ISSUE TITLE
Packer: GOSS version tracking and moving sanity check to goss

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#3763]
### Service(s)

Other

### Summary

- [x] Add a tracking to Goss version with updatecli (from https://github.com/jenkins-infra/packer-images/blob/3e5e07074b49a1d7e02a309c6eb2a3377b40b31f/updatecli/updatecli.d/goss.yml by @dduportal)
- [x] update goss.yaml (add 'exec' step and change title as a deterministic key like java8 or jdk8)
       - Bonus: `s#/usr/local/bin/trivy / trivy#`
- [x]  update updatecli to match those new key (see above)
- [x] Move as much as possible of the sanity checks within packer to goss, and split within either /tests/sanity_goss.yaml or /tests/acceptance_goss.yaml depending on root or jenkins user need. Plan to split between windows/linux/commom the goss tests. - https://github.com/jenkins-infra/packer-images/pull/988
- [x] updatecli (again?) to keep update that new goss structure - https://github.com/jenkins-infra/packer-images/pull/989

**Comment by dduportal** [comment]
Another task to this list: using goss for Windows VMs - https://github.com/jenkins-infra/packer-images/pull/818

**Comment by smerle33** [comment]
Phase 2 of migration for the sanity checks within goss : 
```
git-lfs version
goss version
hadolint version
default java version
jq version
jx-release version
kubectl version
make installed
mvn version
netlify-deploy insrtalled
ssh-agent installed
packer version
parallel installed
python3 version
ruby version
terraform version
unzip installed
updatecli version
vagrant installed
yq version
zip installed
npm installed
playwright version
launchable version
```

**Comment by smerle33** [comment]
TODO
- [ ]    Migrate the windows sanity check to goss
- [ ]     Match updatecli manifests to match the windows checks
- [ ]     Factorize the goss files with linux/windows/common
- [ ]     Match updatecli manifests to match the common
