### ISSUE TITLE
Upgrade to Kubernetes 1.27

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#3948]
### Service(s)

Other

### Summary

Previous upgrade (1.26): https://github.com/jenkins-infra/helpdesk/issues/3683

Depreciation timelines for 1.26 (justifying the upgrade to 1.27):

- Digital Ocean: **28 February 2024** - https://docs.digitalocean.com/products/kubernetes/details/supported-releases/
- Azure AKS: Mar 2024 - https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar
- AWS EKS: June 11, 2024 - https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar

----

Task list:

- [x] Upgrade kubectl within [packer-images AllInOne](https://github.com/jenkins-infra/packer-images/tree/main/updatecli/updatecli.d)
   - [x]  First upgrade the updatecli manifest https://github.com/jenkins-infra/packer-images/pull/1048
   - [x] Then apply the updatecli PR that is produced by this change: https://github.com/jenkins-infra/packer-images/pull/1050
   - [x] Then Apply the Kubernetes-Management PR that will use this new version - https://github.com/jenkins-infra/packer-images/releases/tag/1.53.2 and https://github.com/jenkins-infra/kubernetes-management/pull/4978
- [x] ⚠️ Upgrade kubectl ~~within puppet https://github.com/jenkins-infra/jenkins-infra/blob/bd80ebe3a412702b05165f83a8fc3ba92c4bc891/hieradata/clients/agent.trusted.ci.jenkins.io.yaml#L15 and https://github.com/jenkins-infra/jenkins-infra/blob/bd80ebe3a412702b05165f83a8fc3ba92c4bc891/hieradata/vagrant/common.yaml#L388 OR THE UPDATECLI manifest that update those~~. https://github.com/jenkins-infra/packer-images/blob/6c90ff53c1b616979d02d61e834da3a9f588ae74/updatecli/updatecli.d/kubectl.yaml#L29 don't forget to deploy the image and then use the PR produced by updatecli on kubernetes-management and jenkins-infra repositories to upgrade the image for the AllInOne ⚠️
- [x] Upgrade DOKS (`doks` and `doks-public`) - see below - https://github.com/jenkins-infra/helpdesk/issues/3948#issuecomment-1938993039

- [x] Upgrade AWS EKS (`cik8s` and `eks-public`) - see below - https://github.com/jenkins-infra/helpdesk/issues/3948#issuecomment-1976757473
 
- [x] Upgrade AKS (`privatek8s` and `publick8s`) - see below - https://github.com/jenkins-infra/helpdesk/issues/3948#issuecomment-1991178802 AND https://github.com/jenkins-infra/helpdesk/issues/3948#issuecomment-1991181964

**Comment by smerle33** [comment]
Digital Ocean Clusters:

- [ ] Changelog for Kube 1.27 to be checked with a focus on [kubernetes/kubernetes@master/CHANGELOG/CHANGELOG-1.26.md#urgent-upgrade-notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.27.md#urgent-upgrade-notes)
- [ ] DigitalOcean have their own changelog for their managed components: https://docs.digitalocean.com/products/kubernetes/details/changelog/#1-27-x
- [ ] Preparing upgrade of the cluster, the 2 at the same time (doks-public and doks) no need to disabling or announce for now as it is already unused ... but need to be check is we re activate DO.

**Comment by smerle33** [comment]
For Digital Ocean, to use terraform plan on local computer, we need to provide a token (no doctl auth)
'export DIGITALOCEAN_ACCESS_TOKEN="$(security find-generic-password -a doctl-token-infra -w)";'

**Comment by dduportal** [comment]
Update for DigitalOcean (on behalf of @smerle33 ):

- The upgrade through Terraform was not possible during previous upgrades due to a bug with (Terraform 1.1 + DigitalOcean terraform provider + Kubernetes provider) in the same project. Now that we have Terraform 1.6+, the "hack" we used (using a data source to configure the Kubernetes provider and decouple it from the cluster resource itself) can be removed. See https://github.com/jenkins-infra/digitalocean/pull/179
- The upgrade of `doks-public` from `1.26.12-do.0` to `1.27.10-do.0` looked good on https://github.com/jenkins-infra/digitalocean/pull/179 but failed with the following error:
  
  ```
  Error: Unable to upgrade cluster version: POST https://api.digitalocean.com/v2/kubernetes/clusters/<redacted>/upgrade: 422 (request "<redacted>") invalid upgrade path]
  ```

- Looking at the DigitalOcean console showed there was a patch upgrade to [`1.26.13-do0`](https://docs.digitalocean.com/products/kubernetes/details/changelog/#1.26.13-do.0). This updates should have been applied last Sunday automatically (as per https://github.com/jenkins-infra/digitalocean/blob/41f59716187b14fcc14ba4d4ff14eb8015db2c6f/doks-public-cluster.tf#L21-L24) but it did not.
  - Trying to apply the patch manually from the DigitalOcean cloud console failed with the following errors (along with the 30-ish usual warnings related to `hostpath` and `resource requests/limits` due to datadog and certmanager):

    <img width="816" alt="Capture d’écran 2024-02-16 à 11 43 49" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/b01a4778-7b1e-4851-8870-df91c978ea3a">

    ```
    Validating webhook with a TimeoutSeconds value smaller than 1 second or greater than 29 seconds will block upgrades.
    Resources:
        validating webhook configuration: cert-manager-webhook
    ```

    ```
    Mutating webhook with a TimeoutSeconds value smaller than 1 second or greater than 29 seconds will block upgrades.
    Resources:
        mutating webhook configuration: cert-manager-webhook
    ```

- Short term actions: we decided to start by upgrading to the latest patch so we can retry the upgrade 1.26.x to 1.27.x again with terraform.
  - Manually editing both mutating and validationg webhooks of cert-manager: their default timeout is 30 seconds: we changed it to 25 (note: both `doks-public` and `doks` cluster are [removed from kubernetes-management temporarily](https://github.com/jenkins-infra/kubernetes-management/pull/4982) so no risk of being overriden for now)
  - Ran again the patch upgrade process in the UI for `doks-public`: no more error.
  - Applied with success the `1.26.13-do0` patch to `doks-public`
  - Reverted https://github.com/jenkins-infra/digitalocean/pull/179: the build of the DigitalOcean on the `main` branch is now green.

**Comment by smerle33** [comment]
need to create a updatecli manifest to track kubectl on trusted agent and add it to the "process" for upgrading with the kubectl cli for packer-images.

**Comment by smerle33** [comment]
Update on AWS EKS upgrade: 

- Announcement: Monday 06 Nov. at 14h00 UTC
  - [ ] status.jenkins.io - 
  - [ ] developer mailing list (as ci.jenkins.io need DOKS to be disabled for agents) + jenkins-infra mailing - 
  - [ ] IRC #jenkins-infra - 
  - [ ] Add a banner on ci.jenkins.io
- [ ] Ensure the VPC CNI plugins to be on version ??? or later on: (see last upgrade: plan to upgrade addons manually prior to the next EKS upgrade.)
  - [ ] `eks-public` - https://github.com/jenkins-infra/aws/blob/632f2f3166f79eb80793889250d7abeed5f3a75a/eks-public-cluster.tf#L67
  - [ ] `cik8s` - https://github.com/jenkins-infra/aws/blob/632f2f3166f79eb80793889250d7abeed5f3a75a/cik8s-cluster.tf#L78
- [ ] Disable AWS/BOM Kubernetes Clouds in ci.jenkins.io (puppet hieradata PR) - 
- [ ] Disable kubernetes-management of both clusters (PR) - 
- [ ] Bump Kube version to 1.27 for cik8s
  - [ ] Terraform PR with both Kubernetes and addons update - 
  - [ ] Sanity check with a local helmfile diff (no change)
- [ ] Bump Kube version to 1.27 for eks-public
  - [ ] Terraform PR with both Kubernetes and addons update - 
  - [ ] Sanity check with a local helmfile diff (no change)
- [ ] Terraform jenkins-infra/aws project has a successful build without changes on the `main` branch after the upgrades - https://infra.ci.jenkins.io/job/terraform-jobs/job/aws/job/main/436/
- [ ] Enable kubernetes-management of both clusters (PR) - 
- [ ] Check the ACP service in AWS is up and running
- [ ] Enable AWS/BOM Kubernetes Clouds in ci.jenkins.io (puppet hieradata PR) - 
- [ ] Validate agents can be spawned using a replay of the Infra/acceptance-tests and a simple scripted pipeline `node('cik8s && maven') { sh 'mvn -v' }` and `node('bom && maven') { sh 'mvn -v' }`
- [ ] Close announcements

**Comment by smerle33** [comment]
to get last addon versions : 
```
aws eks describe-addon-versions --profile prod  --kubernetes-version 1.27 --addon-name coredns --region us-east-1
aws eks describe-addon-versions --profile prod  --kubernetes-version 1.27 --addon-name kube-proxy --region us-east-1
aws eks describe-addon-versions --profile prod  --kubernetes-version 1.27 --addon-name vpc-cni --region us-east-1
aws eks describe-addon-versions --profile prod  --kubernetes-version 1.27 --addon-name aws-ebs-csi-driver --region us-east-1
```

coredns ; v1.10.1-eksbuild.7
kube-proxy: v1.27.10-eksbuild.2
vpc-cni: v1.16.4-eksbuild.2
aws-ebs-csi-driver: v1.28.0-eksbuild.1

**Comment by smerle33** [comment]
AZURE 

Update: AKS Upgrade plan **privatek8s**

- [ ] Check changelog:

Current [changelog](https://github.com/Azure/AKS/blob/master/CHANGELOG.md) notable elements for Kubernetes 1.27:


  
**privatek8s**

- Announcement: date/time UTC
  - [ ] Open datetime announcement on status.jenkins.io - 
  - [ ] jenkins-infra mailing - https://groups.google.com/g/jenkins-infra/c/x3sh2Vsveb0
  - [ ] IRC #jenkins-infra - 
- [ ] Disable kubernetes management for privatek8s cluster (remove it from Jenkinsfile_k8s) - 
- [ ] Terraform PR to upgrade cluster to 1.27 but NO merge - 
- [ ] Disable terraform azure job (⚠️ As the upgrade will put infra.ci out of service so need to be run manually)
- [ ] Make sure local (on your machine) repository is up to date and you are logged-in: run a `terraform plan`
- [ ] Merge Terraform PR even without checks (as infra.ci restart will re-enable job)
- [ ] Perform upgrade from local machine
- [ ] Check that helmfile diff still works and shows no change and no warning
- [ ] Wait for infra.ci to be up again
- [ ] Enable kubernetes management for privatek8s cluster and check it runs successfully - 
- [ ] Check terraform job and eventually trigger it for success with no changes
- [ ] Check for release.ci to be up and running: try to allocate agents on release.ci with a job replay (dummy linux and a dummy window)

**Comment by smerle33** [comment]
AZURE 

Update: AKS Upgrade plan **publick8s**

**publick8s**
- Announcement: date/time UTC 
	- [ ] Open datetime announcement on status.jenkins.io - <add link here>
	- [ ] jenkins-dev and jenkins-infra mailing lists - <add link here>
	- [ ] IRC #jenkins-infra - <add link here>
- [ ] Disable kubernetes management for publick8s cluster (remove it from Jenkinsfile_k8s) - <add link here>
- [ ] Terraform PR to upgrade cluster to 1.27 - <add link here>
- [ ] Merge Terraform PR and let the upgrade happen 
- [ ] Check terraform job and eventually trigger it for success with no changes
- [ ] Check that helmfile diff still works and shows no change and no warning
- [ ] Enable kubernetes management for publick8s cluster and check it runs successfully - <add link here>
- [ ] Check for services healthiness (pagerduty, datadog, manual control, logging in on ci.jenkins.io, etc.)
- [ ] Close announcements

**Comment by smerle33** [comment]
![image](https://github.com/jenkins-infra/helpdesk/assets/95630726/9e8eab8e-a283-4d9e-b986-7c80f0be06c8)
