### ISSUE TITLE
Decouple incrementals-publishers from ci.jenkins.io for permissions check

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3955]
### Service(s)

ci.jenkins.io, Incrementals

### Summary

While working on https://github.com/jenkins-infra/helpdesk/issues/3933, we realized that the incremental publisher application relies on ci.jenkins.io to retrieve the permissions list (this was the root cause of #3933).

We have to change the configuration to ensure reports.jenkins.io is used instead: it is a static webserver aims at serving reports (e.g. static files) publicly with high availability.

As per https://github.com/jenkins-infra/incrementals-publisher/?tab=readme-ov-file#environment-variables:

> A URL pointing to the generated repository-permissions-updater output, defaults to https://ci.jenkins.io/job/Infra/job/repository-permissions-updater/job/master/lastSuccessfulBuild/artifact/json/github.index.json

### Task List

- [x] publish the GitHub reports JSON file on reports.jenkins.io
- [x] Update the helm chart to allow passing a custom URL through environment
- [ ] Re-deploy the application with the new URL

**Comment by dduportal** [comment]
Update:

- https://github.com/jenkins-infra/repository-permissions-updater/pull/3773 merged and successful: https://reports.jenkins.io/github.index.json is now present
- https://github.com/jenkins-infra/helm-charts/pull/1073 opened (with handful of tests)

**Comment by dduportal** [comment]
Update:

- Deployed with https://github.com/jenkins-infra/kubernetes-management/pull/4990
- Service restarted and logs are showing it's working as expected on the last PR builds of plugins.
