### ISSUE TITLE
Use JDK21 Platform-wide

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4120]
October 2024: JDK11 is end of life and JDK17 will be the minimum requirement for Jenkins weekly in late June 2024.

The Jenkins infra want to stay on top and support the Jenkins community contribution on the JDK plans: as such we want to use JDK21 as a default everywhere.

This issue is an EPIC to track the related work.

- [x] Provide JDK21 to developer early on ci.jenkins.io
  - [x] EA JDK21 - https://github.com/jenkins-infra/helpdesk/issues/3709
  - [x] GA and further upgrades JDK21 - https://github.com/jenkins-infra/helpdesk/issues/3783 | https://github.com/jenkins-infra/helpdesk/issues/4058
- [x] #4124
- [x] #4123
- [x] #4121
- [x] #4126
- [x] #4125
- [x] #4127
- [x] update the acceptance test harness to use the new jdk as default (TODO add an updatecli manifest) - https://github.com/jenkins-infra/acceptance-tests/pull/42

**Comment by dduportal** [comment]
Update: we have WiP issues related to JDK21 stability and/or memory usage:

- https://github.com/jenkins-infra/helpdesk/issues/3890
- https://github.com/jenkins-infra/helpdesk/issues/3874

**Comment by dduportal** [comment]
Update:

- RPU JDK baseline was changed in https://github.com/jenkins-infra/repository-permissions-updater/pull/3953 but it breaks the trusted.ci execution. Issue to be created to track the fix

**Comment by dduportal** [comment]
Adding to current milestone after https://github.com/jenkins-infra/helpdesk/issues/4623

We need to check which agent images could be removed to avoid having to update too many component.

**Comment by smerle33** [comment]
all done
