### ISSUE TITLE
Move controllers to JDK21 (runtime)

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4123]
We plan the migration on Thursday 22nd of May

The plan is to prepare all the agents to be ready to get used as jdk21 runtime, and do the switch at the same time for controller and most agents. see plan for migration: https://github.com/jenkins-infra/helpdesk/issues/4121#issuecomment-2890355054

kubernetes pods
- [ ] infra.ci.jenkins.io - https://github.com/jenkins-infra/helpdesk/issues/4123#issuecomment-2880178964
- [ ] weekly.ci.jenkins.io - https://github.com/jenkins-infra/helpdesk/issues/4123#issuecomment-2880182001
- [ ] release.ci.jenkins.io - https://github.com/jenkins-infra/helpdesk/issues/4123#issuecomment-2880187505

VMs
- [ ] trusted.ci.jenkins.io, cert.ci.jenkins.io and ci.jenkins.io - https://github.com/jenkins-infra/helpdesk/issues/4123#issuecomment-2880210525

**Comment by smerle33** [comment]
infra.ci.jenkins.io

as per https://github.com/jenkins-infra/docker-jenkins-weeklyci/pull/1344/files for jdk17 we need to prepare the docker container image here: https://github.com/jenkins-infra/docker-jenkins-infraci

**Comment by smerle33** [comment]
weekly.ci.jenkins.io

as for infra, and as per [jenkins-infra/docker-jenkins-weeklyci#1344 (files)](https://github.com/jenkins-infra/docker-jenkins-weeklyci/pull/1344/files) for jdk17 we need to prepare the docker container image here: https://github.com/jenkins-infra/docker-jenkins-weeklyci

**Comment by smerle33** [comment]
release.ci.jenkins.io

as per https://github.com/jenkins-infra/docker-jenkins-lts/pull/772/files for jdk17 we need to prepare the docker container image here: https://github.com/jenkins-infra/docker-jenkins-lts

**Comment by smerle33** [comment]
as per https://github.com/jenkins-infra/jenkins-infra/pull/3018/files for jdk17 we can upgrade all the controller to jdk21 with the same PR on puppet

**Comment by smerle33** [comment]
see plan for migration: https://github.com/jenkins-infra/helpdesk/issues/4121#issuecomment-2890355054

**Comment by dduportal** [comment]
Controllers migrated with success. Let's continue the "minor" agents fixes in #4121
