### ISSUE TITLE
Add JDK21 agents (build)

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4124]
Goal: provide an agent template on each controller (where needed) allowing users to have a default JDK21 when running their pipelines, regardless of the JDK used for running the agent (see https://github.com/jenkins-infra/helpdesk/issues/4121 about agent JDK runtime)

- Developers can use [build tools](https://github.com/jenkins-infra/helpdesk/issues/4125) as an alternative but usage of [pipeline library](https://github.com/jenkins-infra/helpdesk/issues/4126) is preferred

Task list:

- [x] Provide JDK21 in agent templates
  - [x] All in one template
    - [x] JDK21 EA available since https://github.com/jenkins-infra/packer-images/releases/tag/1.20.0 (ref. https://github.com/jenkins-infra/helpdesk/issues/3709)
    - [x] JDK21 LTS available since https://github.com/jenkins-infra/packer-images/releases/tag/1.32.0
  - [x] Windows inbound containers - since https://github.com/jenkins-infra/docker-inbound-agents/pull/98 (ref. https://github.com/jenkins-infra/helpdesk/issues/3709)
- [x] ci.jenkins.io
  - [x] Add a Linux Container template `maven-21` since https://github.com/jenkins-infra/helpdesk/issues/3709
  - [x] Windows Container template (ACI) `maven-21` since https://github.com/jenkins-infra/helpdesk/issues/3709
- [x] trusted.ci.jenkins.io
- [x] cert.ci.jenkins.io
- [ ] infra.ci.jenkins.io

**Comment by dduportal** [comment]
Update: https://github.com/jenkins-infra/helpdesk/issues/4122 indicates that we need to find a solution for trusted.ci.jenkins.io:

- We use Azure VM template which allows running an initialization script when starting the agent process but not setting custom environment variables for the agent process
  - Let's try setting up the JAVA_HOME to JDK21 on a test template => if it work, we can define `maven-xx` labels on trusted.ci to ensure it stays coherent with ci.jio.
  - Otherwise, we'll have to update the pipelines so they define their own env. var JAVA_HOME.
- Note: we'll have to do the same with EC2 in the future though (once we exhaust Azure credits and start using AWS credits)

**Comment by dduportal** [comment]
> Update: #4122 indicates that we need to find a solution for trusted.ci.jenkins.io:
> 
>     * We use Azure VM template which allows running an initialization script when starting the agent process but not setting custom environment variables for the agent process
>       
>       * Let's try setting up the JAVA_HOME to JDK21 on a test template => if it work, we can define `maven-xx` labels on trusted.ci to ensure it stays coherent with ci.jio.
>       * Otherwise, we'll have to update the pipelines so they define their own env. var JAVA_HOME.
> 
>     * Note: we'll have to do the same with EC2 in the future though (once we exhaust Azure credits and start using AWS credits)

Tested with success using Linux Azure VM agents:

- When using inbound mode (such as in ci.jenkins.io) we already have logic in the agent systemD unit file defined inhttps://github.com/jenkins-infra/jenkins-infra/blob/dc673c579eddc81c604638b53b2e6d1f506a0dd7/dist/profile/templates/jenkinscontroller/casc/clouds.yaml.erb#L111C26-L113 => we only have to update the template. Tested with success with the code (JCasc excerpt) below:

```yaml
agentWorkspace: "/home/jenkins/agent"
builtInImage: "Ubuntu 22.04 LTS"
credentialsId: "jenkinsvmagents-userpass"
diskType: "managed"
doNotUseMachineIfInitFails: true
encryptionAtHost: true
ephemeralOSDisk: true
executeInitScriptAsRoot: true
existingStorageAccountName: "cijenkinsioagentssub"
imageReference:
  galleryImageDefinition: "jenkins-agent-ubuntu-22.04-amd64"
  galleryImageVersion: "1.70.1"
  galleryName: "prod_packer_images"
  galleryResourceGroup: "prod-packer-images"
  gallerySubscriptionId: "<redacted>"
imageTopLevelType: "advanced"
initScript: |
  #!/bin/sh
  set -eux

  # Setup Datadog service
  (
    systemctl stop datadog-agent.service
    mkdir -p /var/log/datadog /etc/datadog-agent
    sed 's/api_key:.*/api_key: <redacted>/' /etc/datadog-agent/datadog.yaml.example > /etc/datadog-agent/datadog.yaml
    sed -i 's/# site:.*/site: datadoghq.com/' /etc/datadog-agent/datadog.yaml
    chown dd-agent:dd-agent /etc/datadog-agent/datadog.yaml
    chmod 640 /etc/datadog-agent/datadog.yaml
    chown dd-agent:dd-agent /var/log/datadog
    chmod 770 /var/log/datadog
    systemctl daemon-reload
    systemctl enable datadog-agent.service
    systemctl start datadog-agent.service
  ) 2>&1 | tee /var/log/agent-init-datadog.log
  # Setup Jenkins Agent Service
  (
    # Argument provided by the Azure-VM plugin
    export JENKINS_URL="^${1}" # Always ends with a '/'
    export AGENT_NAME="^${2}"
    export AGENT_SECRET="^${3}"

    export USER=jenkins
    export AGENT_WORKDIR='/home/jenkins/agent'
    export AGENT_JAR="^${AGENT_WORKDIR}/agent.jar"
    export AGENT_SECRETFILE="^${AGENT_WORKDIR}/agent-secret"
    export AGENT_URL="^${JENKINS_URL}computer/^${AGENT_NAME}/jenkins-agent.jnlp"
    export JENKINS_JAVA_OPTS='-XX:+PrintCommandLineFlags'
    export ARTIFACT_CACHING_PROXY_PROVIDER='azure'
    export JAVA_HOME='/opt/jdk-21'
    export JENKINS_JAVA_BIN='/opt/jdk-17/bin/java'

    mkdir -p "^${AGENT_WORKDIR}"
    chown "^${USER}:^${USER}" "^${AGENT_WORKDIR}"
    curl --silent --show-error --location --output "^${AGENT_JAR}" "^${JENKINS_URL}jnlpJars/agent.jar"
    touch "^${AGENT_SECRETFILE}"
    echo "^${AGENT_SECRET}" > "^${AGENT_SECRETFILE}"
    cat <<- EOF >/etc/systemd/system/jenkins-agent.service
    [Unit]
    Description=Jenkins Inbound Agent
    Wants=network.target
    After=network.target

    [Service]
    ExecStart=^${JENKINS_JAVA_BIN} ^${JENKINS_JAVA_OPTS} -jar ^${AGENT_JAR} -jnlpUrl ^${AGENT_URL} -secret @^${AGENT_SECRETFILE} -workDir ^${AGENT_WORKDIR}
    User=^${USER}
    WorkingDirectory=^${AGENT_WORKDIR}
    Restart=on-failure
    RestartSec=10
    Environment="JAVA_HOME=^${JAVA_HOME}"
    Environment="ARTIFACT_CACHING_PROXY_PROVIDER=^${ARTIFACT_CACHING_PROXY_PROVIDER}"
    Environment="PATH=^${JAVA_HOME}/bin:/home/jenkins/.asdf/shims:/home/jenkins/.asdf/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"

    [Install]
    WantedBy=multi-user.target
  EOF

    systemctl daemon-reload
    systemctl enable jenkins-agent
    systemctl start jenkins-agent || systemctl status jenkins-agent
  ) 2>&1 | tee /var/log/agent-init-jenkins.log

  # Remove jenkins user from sudoers
  rm -f /etc/sudoers.d/90-cloud-init-users
labels: "vm-maven-21"
launcher: "inbound"
licenseType: "Classic"
location: "East US 2"
maxVirtualMachinesLimit: 5
maximumDeploymentSize: 10
noOfParallelJobs: 1
osDiskSize: 150
osType: "Linux"
retentionStrategy: "azureVMCloudOnce"
storageAccountNameReferenceType: "existing"
storageAccountType: "Standard_LRS"
subnetName: "public-jenkins-sponsorship-vnet-ci_jenkins_io_agents"
templateDesc: "Test by DDU to have dynamically provisioned Ubuntu 22.04 LTS\
  \ machine using JDK21 for build tools"
templateName: "ubuntu-22-jdk21-ddu"
usageMode: NORMAL
usePrivateIP: true
virtualMachineSize: "Standard_D4ads_v5"
virtualNetworkName: "public-jenkins-sponsorship-vnet"
virtualNetworkResourceGroupName: "public-jenkins-sponsorship"
```

- Also a success with the SSH launcher (used in trusted.ci for instance instead of inbound). The trick was to add  (in the init script code) the same instructions we use in packer-image in https://github.com/jenkins-infra/packer-images/blob/96b1ac213f5c653f695b62389a4c759e60fa8985/provisioning/ubuntu-provision.sh#L364-L365 but setting the default JDK with an even higher priority to override it:

```
export DEFAULT_JDK=/opt/jdk-21
# 2000 is higher than the 1000 provided in template
update-alternatives --install /usr/bin/java java "/opt/jdk-${DEFAULT_JDK}/bin/java" 2000

# Last line: takes precedence over the already defined `JAVA_HOME`
echo "JAVA_HOME=/opt/jdk-${DEFAULT_JDK}" >> /etc/environment
```

**Comment by dduportal** [comment]
> > Update: #4122 indicates that we need to find a solution for trusted.ci.jenkins.io:
> > ```
> > * We use Azure VM template which allows running an initialization script when starting the agent process but not setting custom environment variables for the agent process
> >   
> >   * Let's try setting up the JAVA_HOME to JDK21 on a test template => if it work, we can define `maven-xx` labels on trusted.ci to ensure it stays coherent with ci.jio.
> >   * Otherwise, we'll have to update the pipelines so they define their own env. var JAVA_HOME.
> > 
> > * Note: we'll have to do the same with EC2 in the future though (once we exhaust Azure credits and start using AWS credits)
> > ```
> 
> Tested with success using Linux Azure VM agents:

=> we can start the work to define `maven-17` and `maven-21` labels for Linux Ubuntu VM templates on trusted.ci and cert.ci immediately (cc @smerle33 )
=> With Windows VM, tried the inbound launcher without success: I'm missing how to update env. vars in the current working session (e.g. in the init script): the service launcher does not seem to pick my value (ping @MarkEWaite @timja have you already done this kind of thing?). Ref. init powershell code in https://github.com/jenkins-infra/jenkins-infra/blob/dc673c579eddc81c604638b53b2e6d1f506a0dd7/dist/profile/templates/jenkinscontroller/casc/clouds.yaml.erb#L24-L50 which starts the inbound service stuff

**Comment by timja** [comment]
> Also a success with the SSH launcher

You can also simply set the `javaPath` variable in JCasC for SSH launcher

> inbound launcher without success for Windows

Your code looks fine, I'd login to the agent and cat the file to see its been replaced appropriately and check the logs for the service (along with trying to start it manually if needed)

**Comment by dduportal** [comment]
> > Also a success with the SSH launcher
> 
> You can also simply set the `javaPath` variable in JCasC for SSH launcher

We already do this (ref. https://github.com/jenkins-infra/jenkins-infra/blob/dc673c579eddc81c604638b53b2e6d1f506a0dd7/dist/profile/templates/jenkinscontroller/casc/clouds.yaml.erb#L153).
But the JCasC `javaPath` attribute is only used to specify a JDK binary for the agent runtime (will be tracked in https://github.com/jenkins-infra/helpdesk/issues/4121).

Here, we want the set the default java available for builds, which is set by 2 variables:
- Set up or override `JAVA_HOME` (picked by Maven for instance)
- Update `PATH` to have `JAVA_HOME/bin` so a call to `java` (or `java.exe`) would resolve to the expected Java

On Kubernetes plugin or EC2 plugin, we define the environment variables in the Jenkins Cloud config UI and the variables are applied to the `agent.jar` process when it starts.
But with AzureVM, this feature does not exist as far as I can tell: we rely on the custom init script instead.

On Linux, we have solutions due to the init script using SystemD (inbound launcher) or update-alternative (Ubuntu) to solve the problem => no complicated env. loading path to manage.

But on Windows I'm not sure which solution to take: we usually set up the registry to have the env. vars setup which requires a reboot/restart/reload/reloggin for this change to be taken in account. As we tend to use packer and Docker, this problem do not exist (we build the image, and then when it is instanciated, the new env. is loaded).
=> in the case here, the init script of the AzureVM plugin does not re-log/reload so the new env. var values are not picked up by the agent.jar process.

**Comment by timja** [comment]
Have a look at this for Windows: https://github.com/winsw/winsw/blob/v3/docs/xml-config-file.md

**Comment by dduportal** [comment]
> Have a look at this for Windows: https://github.com/winsw/winsw/blob/v3/docs/xml-config-file.md

Coool, that will do the trick!

**Comment by dduportal** [comment]
Update:

- WiP on inbound agent JDK17 and JDK21 for ci.jenkins.io (only): https://github.com/jenkins-infra/jenkins-infra/pull/3540

**Comment by dduportal** [comment]
Update:

- https://github.com/jenkins-infra/jenkins-infra/pull/3540 was merged with success
- Also added https://github.com/jenkins-infra/jenkins-infra/pull/3546 to "clean up" Linux VM templates on ci.jenkins.io
- Updated documentation accordingly: https://github.com/jenkins-infra/documentation/commit/d9830fa87815e26a0ab0cee4fc4aacb6911ea834
- And also acceptance tests: https://github.com/jenkins-infra/acceptance-tests/blob/check-agent-availability/Jenkinsfile#L17

**Comment by dduportal** [comment]
Update: cert.ci.jenkins.io can now utilizes JDK17 and JDK21 without requiring Jenkins tools installation:

- https://github.com/jenkins-infra/jenkins-infra/pull/3564 => applied on cert.ci with https://github.com/jenkins-infra/jenkins-infra/pull/3565
  - Fixup with https://github.com/jenkins-infra/jenkins-infra/pull/3584
- cert.ci runbook updated: https://github.com/jenkins-infra/runbooks/commit/6c96cabc019ca413d33ff2fded351a14915d83c7 (cc @daniel-beck @wadeck)
- The infra-team-validate-agents on cert.ci has been updated with the following pipeline:

```
parallel "linux": {
  stage('Test default "linux" agent label with tools') {
    node('linux') {
      sh 'java -version'
      sh 'mvn -v'
      
      jdk21 = tool name: "jdk-21", type: 'jdk'
      withEnv(["PATH+JDK=${jdk21}/bin", "JAVA_HOME=${jdk21}"]) {
        sh 'mvn -v'
      }

      jdk17 = tool name: "jdk-17", type: 'jdk'
      withEnv(["PATH+JDK=${jdk17}/bin", "JAVA_HOME=${jdk17}"]) {
        sh 'mvn -v'
      }

      jdk11 = tool name: "jdk-11", type: 'jdk'
      withEnv(["PATH+JDK=${jdk11}/bin", "JAVA_HOME=${jdk11}"]) {
        sh 'mvn -v'
      }
    
      jdk8 = tool name: "jdk-8", type: 'jdk'
      withEnv(["PATH+JDK=${jdk8}/bin", "JAVA_HOME=${jdk8}"]) {
          sh 'mvn -v'
      }
    }
  }
},
"windows": {
  stage('Test default "windows" agent label with tools') {
    node('windows') {
      bat 'java -version'
      bat 'mvn -v'
      
      jdk21 = tool name: "jdk-21", type: 'jdk'
      withEnv(["PATH+JDK=${jdk21}/bin", "JAVA_HOME=${jdk21}"]) {
        bat 'mvn -v'
      }

      jdk17 = tool name: "jdk-17", type: 'jdk'
      withEnv(["PATH+JDK=${jdk17}/bin", "JAVA_HOME=${jdk17}"]) {
        bat 'mvn -v'
      }

      jdk11 = tool name: "jdk-11", type: 'jdk'
      withEnv(["PATH+JDK=${jdk11}/bin", "JAVA_HOME=${jdk11}"]) {
        bat 'mvn -v'
      }
    
      jdk8 = tool name: "jdk-8", type: 'jdk'
      withEnv(["PATH+JDK=${jdk8}/bin", "JAVA_HOME=${jdk8}"]) {
        bat 'mvn -v'
      }
    }
  }
},
"ubuntu-22-amd64-maven-11": {
  stage('Test specific "ubuntu-22-amd64-maven-11" agent label') {
    node('ubuntu-22-amd64-maven-11') {
      sh 'java -version'
      sh 'mvn -v'
    }
  }
},
"ubuntu-22-amd64-maven-17": {
  stage('Test specific "ubuntu-22-amd64-maven-17" agent label') {
    node('ubuntu-22-amd64-maven-17') {
      sh 'java -version'
      sh 'mvn -v'
    }
  }
},
"ubuntu-22-amd64-maven-21": {
  stage('Test specific "ubuntu-22-amd64-maven-21" agent label') {
    node('ubuntu-22-amd64-maven-21') {
      sh 'java -version'
      sh 'mvn -v'
    }
  }
}
```

**Comment by dduportal** [comment]
Update: trusted.ci.jenkins.io is now providing JDK17 and JDK21

- Puppet code change: https://github.com/jenkins-infra/jenkins-infra/pull/3566 was deployed successfully
- The job https://trusted.ci.jenkins.io:1443/job/jenkins-infra/job/agent-checks/ was updated to test, once a day, the default templates(`linux` and `windows`) along with the 3 new ones
  - Note: tools are using the `jdkXX` pattern instead of the `jdk-XX` pattern like on cert.ci. We have a discrepancy here
  - Note: checked labels are `maven-XX` to fit to the ci.jenkins.io patter, (as we have pipeline runs on both ci.jio and trusted.ci.jio)

<details>
<summary>Click me to view pipeline code</summary>

```groovy
parallel "linux": {
  stage('Test default "linux" agent label with tools') {
    node('linux') {
      sh 'java -version'
      sh 'mvn -v'
      
      jdk21 = tool name: "jdk21", type: 'jdk'
      withEnv(["PATH+JDK=${jdk21}/bin", "JAVA_HOME=${jdk21}"]) {
        sh 'mvn -v'
      }

      jdk17 = tool name: "jdk17", type: 'jdk'
      withEnv(["PATH+JDK=${jdk17}/bin", "JAVA_HOME=${jdk17}"]) {
        sh 'mvn -v'
      }

      jdk11 = tool name: "jdk11", type: 'jdk'
      withEnv(["PATH+JDK=${jdk11}/bin", "JAVA_HOME=${jdk11}"]) {
        sh 'mvn -v'
      }
    
      jdk8 = tool name: "jdk8", type: 'jdk'
      withEnv(["PATH+JDK=${jdk8}/bin", "JAVA_HOME=${jdk8}"]) {
          sh 'mvn -v'
      }
    }
  }
},
"windows": {
  stage('Test default "windows" agent label with tools') {
    node('windows') {
      bat 'java -version'
      bat 'mvn -v'
      
      jdk21 = tool name: "jdk21", type: 'jdk'
      withEnv(["PATH+JDK=${jdk21}/bin", "JAVA_HOME=${jdk21}"]) {
        bat 'mvn -v'
      }

      jdk17 = tool name: "jdk17", type: 'jdk'
      withEnv(["PATH+JDK=${jdk17}/bin", "JAVA_HOME=${jdk17}"]) {
        bat 'mvn -v'
      }

      jdk11 = tool name: "jdk11", type: 'jdk'
      withEnv(["PATH+JDK=${jdk11}/bin", "JAVA_HOME=${jdk11}"]) {
        bat 'mvn -v'
      }
    
      jdk8 = tool name: "jdk8", type: 'jdk'
      withEnv(["PATH+JDK=${jdk8}/bin", "JAVA_HOME=${jdk8}"]) {
        bat 'mvn -v'
      }
    }
  }
},
"ubuntu-22-amd64-maven-11": {
  stage('Test specific "ubuntu-22-amd64-maven-11" agent label') {
    node('maven-11') {
      sh 'java -version'
      sh 'mvn -v'
    }
  }
},
"ubuntu-22-amd64-maven-17": {
  stage('Test specific "ubuntu-22-amd64-maven-17" agent label') {
    node('maven-17') {
      sh 'java -version'
      sh 'mvn -v'
    }
  }
},
"ubuntu-22-amd64-maven-21": {
  stage('Test specific "ubuntu-22-amd64-maven-21" agent label') {
    node('maven-21') {
      sh 'java -version'
      sh 'mvn -v'
    }
  }
}
```

</details>

**Comment by dduportal** [comment]
Next step: transplant JCasc changes to https://github.com/jenkins-infra/kubernetes-management/blob/main/config/jenkins_infra.ci.jenkins.io.yaml

**Comment by dduportal** [comment]
Update: the Windows inbound agents are now using the proper `javaHome` environment variable as per https://github.com/jenkins-infra/jenkins-infra/pull/3594.

Next steps:

- infra.ci.jenkins.io (ref. https://github.com/jenkins-infra/helpdesk/issues/4124#issuecomment-2277377553)
- Verify that the same technique (as per https://github.com/Azure/jenkins/blob/ba240aa8c2392577f607646e841b83ebcf554992/agents_scripts/Jenkins-Windows-Init-Script-SSH.ps1#L14-L16) works with our Windows SSH agents setup
  - If yes: then proceed to set up the Puppet template and apply to trusted and cert.ci

**Comment by dduportal** [comment]
@jayfranco999 , along with the infra.ci template updates, could you also add 2 new Windows 2019 VM template (JDK17 and JDK21) for ci.jenkins.io (Inbound launchers)?

**Comment by dduportal** [comment]
- https://github.com/jenkins-infra/helpdesk/issues/4244 opened to fix an infra.ci error found while deploying the Linux agents
- Azure Windows SSH agents:
  - Adding variables during the initScript of an Azure SSH agent behaves as expected: `JAVA_HOME` works well and Maven uses the correct Java
  - *However* OpenSSH server seems to filter the `Path` variable: we can add to it but we cannot remove the existing elements from it. As such, I would want to remove defining a default JDK in the Windows packer image (https://github.com/jenkins-infra/packer-images/blob/bc253d92b0d51d20f7b77ff8ed1cf7f25ab171db/provisioning/windows-provision.ps1#L300) and only define it during the init script

**Comment by dduportal** [comment]
Update: no solution works to change the `Path` variables with SSH Windows agent:

- Tried changing Path on the 3 levels (Machine, User, Process)
- Tried restarting SSH server as part of the init script
- Tried the `setx` commands
- Tried changing the OpenSSH and restart

=> The initScript (not cloud init!) being executed in the context of a SSH session, I fear the only way is to change the template setup.

As such, let's remove any definition of a default JDK on the jenkins-infra/packer-images.
We'll let @jayfranco999 work on this

**Comment by jayfranco999** [comment]
Update: BREAKING CHANGE: removing the default_jdk env variable will introduce failure in goss tess harness for windows SSH agents and will result in build failures.

As per https://github.com/jenkins-infra/helpdesk/issues/4124#issuecomment-2307122480 :

Any definition of a 'default JDK' and 'update-alternatives' on the jenkins-infra/packer-images has been removed from the ubuntu-provisioning script. The corresponding goss test patch has also been added to the goss test harness to check installation of maven.

Next steps are to introduce the same feature parity for the windows SSH agents with updated goss test harness for it.

**Comment by jayfranco999** [comment]
Update: 

BREAKING CHANGE: All definitions of Default JDK has been removed from windows-2019 SSH agents.

As per https://github.com/jenkins-infra/helpdesk/issues/4124#issuecomment-2307122480 :

If the solution holds good, we can proceed to remove all definitions of Default JDK from jenkins-infra/packer-images and introduce feature parity in the goss-common tests for both Linux and Windows SSH agents.

**Comment by jayfranco999** [comment]
Update: https://github.com/jenkins-infra/jenkins-infra/pull/3656

Added init script to handle javaHome path for Windows SSH agents since default_jdk is no longer used.

Added the following windows SSH AZ VM templates:

cert.ci:
win-2019-maven-17, win-2019-maven-21

trusted.ci
win-2019-maven-17, win-2019-maven-21
win-2022-maven-17, win-2022-maven-21

**Comment by dduportal** [comment]
Update:

- ci.jio, cert.ci.jio and trusted.cio now all have JDK11, JDK17 and JDK21 agents for both Linux and Windows, with label parity 🥳 
  - https://github.com/jenkins-infra/jenkins-infra/pull/3656
  - https://github.com/jenkins-infra/jenkins-infra/pull/3659

@jayfranco999 there is nothing to do on infra.ci for the Windows agents. We use them only for Docker, so no need to clutter the configuration. We'll switch the existing Windows templates (on infra.ci) from JDK11 to JDK21 as part of https://github.com/jenkins-infra/helpdesk/issues/4127
