### ISSUE TITLE
Upgrade to Kubernetes 1.28

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4144]
Per https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar, Microsoft stops supporting Kubernetes 1.27 in July 2024.

As such, we must upgrade our [Kubernetes clusters to 1.28](https://kubernetes.io/blog/2023/08/15/kubernetes-v1-28-release/).

Last issue for 1.27 was: https://github.com/jenkins-infra/helpdesk/issues/3948. Since last issue, we [got rid](https://github.com/jenkins-infra/helpdesk/issues/3954) of AWS and DigitalOcean clusters: we only have 4 Azure AKS clusters now.

----

Task list:

- [x] Upgrade kubectl within [packer-images All-in-One](https://github.com/jenkins-infra/packer-images/tree/main/updatecli/updatecli.d)
   - [x]  First upgrade the updatecli manifest (https://github.com/jenkins-infra/packer-images/pull/1239)
   - [x] Then apply the updatecli PR that is produced by this change: (https://github.com/jenkins-infra/packer-images/pull/1240)
   - [x] Trigger a release of the packer-images (https://github.com/jenkins-infra/packer-images/releases/tag/1.73.1)
   - [x] Then apply the Kubernetes-Management PR that will use this new version -(https://github.com/jenkins-infra/kubernetes-management/pull/5331)
   - [x] Also apply the [puppet (jenkins-infra/jenkins-infra)](https://github.com/jenkins-infra/jenkins-infra) PR with the new version  - (https://github.com/jenkins-infra/jenkins-infra/pull/3485)
   --
- [x] Check AKS changelog for 1.28 - https://github.com/Azure/AKS/blob/master/CHANGELOG.md#release-2023-11-05 
- [x] Upgrade AKS cluster `infracijio-agents-1` [(details)](https://github.com/jenkins-infra/helpdesk/issues/4144#issuecomment-2178169723)
- [x] Upgrade AKS cluster `cijenkinsio-agents-1` [(details)](https://github.com/jenkins-infra/helpdesk/issues/4144#issuecomment-2182701643)
- [x] Upgrade AKS cluster `privatek8s` [(details)](https://github.com/jenkins-infra/helpdesk/issues/4144#issuecomment-2190936375)
- [x] Upgrade AKS cluster `publick8s` [(details)](https://github.com/jenkins-infra/helpdesk/issues/4144#issuecomment-2196274746)
 - [x] Add Logo ;)
 - [x] Open issue for next Kubernetes version

**Comment by smerle33** [comment]
**infracijio-agents-1**

- [ ] Announcement:  no announcement needed as the cluster is not used yet
- [ ] Disable kubernetes management for infracijio-agents-1 cluster (remove it from Jenkinsfile_k8s) - <link pr>
- [ ] Terraform PR to upgrade cluster to 1.28 but NO merge - <link pr>
	- [ ] checks that all checks are ok 	
	- [ ] Merge the PR
- [ ] Enable kubernetes management for infracijio-agents-1 cluster and check it runs successfully - 
- [ ] Check terraform job and eventually trigger it for success with no changes

**Comment by smerle33** [comment]
**cijioagents1**

We plan to handle this upgrade Tuesday 25 of june morning Paris time

- [ ] Announcements:  
  - [ ] status.jenkins.io - <pr link>
  - [ ] developer mailing list + jenkins-infra mailing - @dduportal and @smerle33 
  - [ ] IRC #jenkins-infra - @dduportal and @smerle33 
  - [ ] Add a banner on ci.jenkins.io - @dduportal and @smerle33 
- [ ] Disable kubernetes management for cijio-agents-1 cluster (remove it from Jenkinsfile_k8s) - <pr link>
- [ ] Terraform PR to upgrade cluster to `1.28.9` but NO merge - <pr link>
	- [ ] checks that all checks are ok 	
	- [ ] Merge the PR
- [ ] Enable kubernetes management for infracijio-agents-1 cluster and check it runs successfully - <pr link>
- [ ] Check terraform job and eventually trigger it for success with no changes - <pr link>
- [ ] Close Annoucements
  - [ ] status.jenkins.io - <pr link>
  - [ ] developer mailing list + jenkins-infra mailing - @dduportal and @smerle33 
  - [ ] IRC #jenkins-infra - @dduportal and @smerle33 
  - [ ] Add a banner on ci.jenkins.io - @dduportal and @smerle33

**Comment by smerle33** [comment]
Update on publick8s Azure AKS upgrade: 

- [ ] Changelog for Kube 1.28 to be checked with a focus on [kubernetes/kubernetes@master/CHANGELOG/CHANGELOG-1.28.md#urgent-upgrade-notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.28.md#urgent-upgrade-notes)
- [ ] Changelog focus on Azure : https://github.com/Azure/AKS/blob/master/CHANGELOG.md?rgh-link-date=2024-06-18T11%3A54%3A32Z#release-2023-11-05
- Announcement: Thursday 4 March at 07h00 UTC
  - [ ] status.jenkins.io - <pr link>
  - [ ] developer mailing list (as ci.jenkins.io) + jenkins-infra mailing - <group email link>
  - [ ] IRC #jenkins-infra - <pr link>
  - [ ] Add a banner on ci.jenkins.io <pr link>
- [ ] Disable kubernetes-management for publick8s clusters - <pr link>
- [ ] Bump Kube version to 1.28 for publick8s - <pr link>
- [ ] Terraform jenkins-infra/azure project has a successful build without changes on the `main` branch after the upgrades - <build link>
- [ ] Enable kubernetes-management back for publick8s - <pr link>
- [ ] Check the ACP service in azure/publick8s is up and running use this link https://repo.azure.jenkins.io/public/org/jenkins-ci/plugins/plugin/4.61/
- [ ] Validate agents can be spawned using a replay of the Infra/acceptance-tests and a simple scripted pipeline `node('maven') { sh 'mvn -v' }` and `node('maven-bom') { sh 'mvn -v' } ` - <builds links>
- [ ] Close announcements
  - [ ] status.jenkins.io - <pr link>
  - [ ] developer mailing list (as ci.jenkins.io) + jenkins-infra mailing - <group email link>
  - [ ] IRC #jenkins-infra - <pr link>

**Comment by jayfranco999** [comment]
![image](https://github.com/jenkins-infra/helpdesk/assets/79799016/6256bce4-222e-4625-8c65-7ba6d1ffdf9e)
