### ISSUE TITLE
Upgrade to Kubernetes 1.30

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4258]
Per https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar, Microsoft stops supporting Kubernetes 1.29 in March 2025.

- Note: EKS has the same support expiration policy for 1.29 (March 2025) - https://github.com/jenkins-infra/helpdesk/issues/4258

As such, we must upgrade our 

<details>
  <summary>AZURE: 1.30.7 </summary>

https://kubernetes.io/blog/2024/04/17/kubernetes-v1-30-release/
</details>

<details>
  <summary>AWS: 1.30.9 </summary>

`aws eks describe-cluster-versions --region us-east-2 --profile=terraform-admin | jq '.clusterVersions[] | select(.clusterVersion == "1.30")'`

```
{
    "clusterVersion": "1.30",
    "clusterType": "eks",
    "defaultPlatformVersion": "eks.27",
    "defaultVersion": false,
    "releaseDate": "2024-05-23T02:00:00+02:00",
    "endOfStandardSupportDate": "2025-07-23T02:00:00+02:00",
    "endOfExtendedSupportDate": "2026-07-23T02:00:00+02:00",
    "status": "STANDARD_SUPPORT",
    "kubernetesPatchVersion": "1.30.9"
}
```

</details>
Last issue for 1.29 was: https://github.com/jenkins-infra/helpdesk/issues/4161

----

Task list:

- [x] Upgrade kubectl within [packer-images All-in-One](https://github.com/jenkins-infra/packer-images/tree/main/updatecli/updatecli.d)
   - [x]  First upgrade the updatecli manifest - https://github.com/jenkins-infra/packer-images/pull/1733
   - [x] Then apply the updatecli PR that is produced by this change: - https://github.com/jenkins-infra/packer-images/pull/1737
   - [x] Trigger a release of the packer-images - https://github.com/jenkins-infra/packer-images/releases/tag/2.28.1
   - [x] Then apply the Kubernetes-Management PR that will use this new version - https://github.com/jenkins-infra/kubernetes-management/pull/6231
   - [x] Also apply the [puppet (jenkins-infra/jenkins-infra)](https://github.com/jenkins-infra/jenkins-infra) - https://github.com/jenkins-infra/jenkins-infra/pull/3891

- [x] Check AKS changelog for 1.30 - https://github.com/Azure/AKS/blob/master/CHANGELOG.md and AWS changelog - https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions-standard.html#kubernetes-1-30
- [x] Upgrade AKS cluster `cijenkinsio-agents-1` [(details)](https://github.com/jenkins-infra/helpdesk/issues/4258#issuecomment-2663661996) planned today Tuesday 18 February
- [x] Upgrade AWS cluster `cijenkinsio-agents-2` [(details)](https://github.com/jenkins-infra/helpdesk/issues/4258#issuecomment-2666362598)  planned Wednesday 19 February
- [x] Upgrade AKS cluster `infracijio-agents-1` [(details)](https://github.com/jenkins-infra/helpdesk/issues/4258#issuecomment-2663185312) planned Wednesday 19 February
- [x] Upgrade AKS cluster `privatek8s`[(details)](https://github.com/jenkins-infra/helpdesk/issues/4258#issuecomment-2668175339) planned Thursday 20 of February morning paris time 
- [x] Upgrade AKS cluster `publick8s` [(details)](https://github.com/jenkins-infra/helpdesk/issues/4258#issuecomment-2663553626) planned Thursday 20 of February afternoon paris time 
- [x] Add Logo ;)
- [x] Open issue for next Kubernetes version

**Comment by dduportal** [comment]
Update: delayed triage until October 2024

**Comment by smerle33** [comment]
packer-image release was stuck and relaunched https://infra.ci.jenkins.io/job/infra-tools/job/packer-images/view/tags/job/2.28.1/

**Comment by smerle33** [comment]
**infracijio-agents-1**

- [ ] Announcement: jenkins-infra element channel
- [ ] Disable kubernetes management for infracijio-agents-1 cluster (remove it from Jenkinsfile_k8s) - <kubernetes-management pr link>

> [!WARNING]  
> Terraform upgrade must be performed manually otherwise it will upgrade the cluster where agents are currently performing, leading to build failure

- [ ] Upgrade cluster to 1.30 with Terraform (Azure)
  - [ ] PR with checks all green: <azure pr link>
  - [ ] Prepare local (admin laptop) terraform plan
  - [ ] Disable Terraform Azure Job in infra.ci
  - [ ] Merge the PR
  - ⚠️ Note that AKS version is not always exactly the same patch as `kubectl `. Always use the AKS changelog to check (or the `az` CLI). here should be `1.30.7`
  - [ ] Deploy from local admin laptop
  - [ ] Enable Terraform Azure Job in infra.ci and run it once with success
- [ ] Enable kubernetes management for infracijio-agents-1 cluster and check it runs successfully - <kubernetes-management pr link>

----

**Comment by smerle33** [comment]
Check of the Kubernetes 1.30 and AKS changelogs:

Nothing for us on

	- deprecation https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.30.md#deprecation
	
Notes: 
	- NOTE: Azure portal mentions we're using a deprecated resource (ComponentStatus). Culprit is the datadog helm chart (see https://github.com/DataDog/helm-charts/issues/961) but it's should still work for 1.30 as it's still in the master branch source code https://github.com/liggitt/kubernetes/blob/4e7e14203db8cde906604b057b1b2a8a15e8a50d/pkg/apis/core/types.go#L6377

**Comment by smerle33** [comment]
Update: `publick8s` cluster upgrade:

> [!WARNING]  
> Your cluster was found to be using the deprecated In-Tree Persistent Volume (PV) storage class. 
> one PV for `ldap-backup` using `azureFile`
> need to upgrade with https://learn.microsoft.com/en-us/azure/aks/csi-migrate-in-tree-volumes

- [ ] Announcement:
  - [ ] Open datetime announcement on status.jenkins.io - status pr link
  - [ ] [developer mailing list (Authentication outage due to LDAP restart)](https://groups.google.com/g/jenkinsci-dev) -groups.google.com message link
  - [ ] IRC #jenkins-infra
- [ ] Disable kubernetes management for publick8s cluster (remove it from Jenkinsfile_k8s) - kubernetes-management pr link
- [ ] Terraform PR to upgrade cluster - azure pr link 
- [ ] Merge Terraform PR and let the upgrade happen 
- [ ] Check the LDAP restart successfully once upgrade is performed. If the pod restarted and is running, try the service by logging-in on ci.jenkins.io and repo.jenkins-ci.org
- [ ] Check terraform job and eventually trigger it for success with no changes - https://infra.ci.jenkins.io/job/terraform-jobs/job/azure/job/main/`lastid`
- [ ] Enable kubernetes management and revert exclusion of `publick8s` cluster, checking both diff and apply run successfully -  kubernetes-management pr link
- [ ] Check the pagerduty alerts are all gone
- [ ] Close announcements

**Comment by smerle33** [comment]
**cijioagents2**

We plan to handle this upgrade Wednesday 19 February

- [ ] Announcements:  
  - [ ] status.jenkins.io - https://github.com/jenkins-infra/status/pull/id
  - [ ] developer mailing list - https://groups.google.com/g/jenkinsci-dev/c/534G42tOf1A
  - [ ] IRC #jenkins-infra - 
  - [ ] Add a banner on ci.jenkins.io - 
- [ ] Disable kubernetes management for cijio-agents-2 cluster (remove it from Jenkinsfile_k8s) - https://github.com/jenkins-infra/kubernetes-management/pull/5609
- [ ] Disable the 2 clouds defined in ci.jenkins.io on puppet (jenkins-infra/jenkins-infra) for the operation `ci.jenkins.io-agents-1-bom` and `ci.jenkins.io-agents-1` - https://github.com/jenkins-infra/jenkins-infra/pull/3619
- [ ] Terraform PR to upgrade cluster to `1.29.7` but NO merge - https://github.com/jenkins-infra/azure/pull/808
	- [ ] Verify all checks are ok
	- [ ] Merge the PR
	- [ ] Verify upgraded is performed with no error
- [ ] Enable kubernetes management for ci.jio-agents-2 cluster and check it runs successfully - https://github.com/jenkins-infra/kubernetes-management/pull/5611
- [ ] Re-Enable the 2 ci.jio puppet clouds and check container agents are scheduled with the Infra/acceptance-test job - https://github.com/jenkins-infra/jenkins-infra/pull/3620
- [ ] Close Annoucements
  - [ ] status.jenkins.io - https://github.com/jenkins-infra/status/pull/534
  - [ ] developer mailing list + jenkins-infra mailing 
  - [ ] IRC #jenkins-infra
  - [ ] Remove the banner on ci.jenkins.io

**Comment by smerle33** [comment]
**privatek8s**  on AZURE cluster upgrade:

- [ ] Announcement:
  - [ ] Open datetime announcement on status.jenkins.io - https://github.com/jenkins-infra/status/pull/535
  - [ ] IRC #jenkins-infra
- [ ] Disable kubernetes management for privatek8s cluster (remove it from Jenkinsfile_k8s) - https://github.com/jenkins-infra/kubernetes-management/pull/5614
- [ ] Terraform PR to upgrade cluster - https://github.com/jenkins-infra/azure/pull/809
- [ ] Merge Terraform PR and let the upgrade happen 
- [ ] Check terraform job and eventually trigger it for success with no changes - https://infra.ci.jenkins.io/job/terraform-jobs/job/azure/job/main/1334
- [ ] Enable kubernetes management and revert exclusion of `privatek8s` cluster, checking both diff and apply run successfully - https://github.com/jenkins-infra/kubernetes-management/pull/5615
- [ ] Check for services healthiness (pagerduty, datadog, manual control, logging in on infra.ci.jenkins.io/release.ci.jenkins.io with the `Infra Agents Health` job https://release.ci.jenkins.io/job/Infra%20Agents%20Health/)
- [ ] Close announcements

**Comment by smerle33** [comment]
![Image](https://github.com/user-attachments/assets/eeb8471c-d4f8-45c3-8289-ece6202c0794)
