### ISSUE TITLE
[GeoIP database][subtask] Add a `CronJob` geoip updater task for mirrorbits

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#4278]
- We need to find another implementation (most probably a cron job running every 72 and uploading data to the file share using `azcopy`) => an infra.ci job ?

_Originally posted by @dduportal in https://github.com/jenkins-infra/helpdesk/issues/4240#issuecomment-2308235860_
           

We need a specific Docker Image with both geoipupdater and azcopy : https://github.com/jenkins-infra/helpdesk/issues/4278#issuecomment-2328400184
We will then be able to schedule a cronjob from kubernetes to update the geoip database directly in the file share.

**Comment by smerle33** [comment]
WIP Custom Docker Image:
need to perform with 2 FROM, one with official azcopy support and the official geoipupdate.

- [ ] -> use the TTD to ensure this contract
- [ ] -> provide a multiplatform image (arm64/intel)
- [ ] -> create a dedicated repository

**Comment by dduportal** [comment]
Update: with https://github.com/jenkins-infra/azure/pull/844, we now have an Azure Client (App + SP + password) allowed to get temp. token to write on the file share.

Can be tested locally (**inside** the docker image) and will be added in SOPS (and used as kubernetes secret passed as pod env var) by the chart

**Comment by dduportal** [comment]
Update:

- Repository https://github.com/jenkins-infra/docker-geoipupdate created to host the Docker image needed for implementing this CronJob
  - [x] Initial implementation: https://github.com/jenkins-infra/docker-geoipupdate/pull/1
  - [x] Updatecli tracking of some of its dependencies: https://github.com/jenkins-infra/docker-geoipupdate/pull/2
  - [ ] TODO: Set up GitHub usual settings, inspired from another `docker-*` repo (permissions, branch protection, rpeository settings)
  - [ ] TODO: add this repository in the infra.ci GHA apps for Docker and updatecli
- [ ] infra.ci Jobs configuration for building this image: TODO (Docker at least, ideally updatecli'(s jobs)
- [ ] DockerHub "repository" to be created (and set up with proper permissions)

**Comment by dduportal** [comment]
>     * [x]  DockerHub "repository" to be created (and set up with proper permissions) - https://hub.docker.com/repository/docker/jenkinsciinfra/geoipupdate/general

@smerle33 please check that the DockerHub repository name is properly specified for the image name in the `Jenkinsfile_k8s`

**Comment by dduportal** [comment]
> * Set up release-drafter (setting file + GHA files) to ensure a `next` draft release is generated (otherwise the infra.ci `main` branch build will fail)

Additional task (worth a PR @smerle33 )

**Comment by smerle33** [comment]
specific repository done: https://github.com/jenkins-infra/docker-geoipupdate
release-drafter setup: https://github.com/jenkins-infra/docker-geoipupdate/blob/main/.github/workflows/release-drafter.yml
and gha updated (by damien)
first release deployed on a dedicated docker hub repository: https://hub.docker.com/r/jenkinsciinfra/geoipupdate/tags

next step: helm/helm chart to integrate to our kubernetes.

**Comment by smerle33** [comment]
updating the docker image to be able to specify the fileshare (hardcoded until then) https://github.com/jenkins-infra/docker-geoipupdate/pull/11
and remove the mount on the fileshare as we use azcopy for now (we may roll back if we switch to use rsync)

**Comment by smerle33** [comment]
added a dryrun option to avoid hitting geoip rate limit during test.

**Comment by smerle33** [comment]
cronjob in production, ran manually once with success

![image](https://github.com/user-attachments/assets/2bb44b39-40e5-4921-bbeb-13c99054c89e)

**Comment by dduportal** [comment]
FTR: this routine (the Kubernetes cronjob) has been deprovisionned by https://github.com/jenkins-infra/kubernetes-management/pull/7002 as part of [switching the GeoIP custom volume into the all in one NFS](https://github.com/jenkins-infra/helpdesk/issues/4767) (for performance reasons with the reliability/safety risk involved with a all in one shared storage).


Routine is moving to an infra.ci.jenkins.io job as part of https://github.com/jenkins-infra/helpdesk/issues/4878
