### ISSUE TITLE
Switch from Jira Issues to Github Issues for the INFRA project

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#9]
# INFRA issues migration from Jira to Github
As of the 11th of January 2022, all INFRA projects issues have been migrated from Jira to this repository on Github.

## Process

- [x] Create this repository
- [x] Import the current issues from https://issues.jenkins.io/projects/INFRA/issues ([INFRA-1 to INFRA-3180](https://github.com/jenkins-infra/helpdesk/issues?q=is%3Aissue+sort%3Acreated-desc+label%3Aimported-jira-issue))

- [x] Publish a comment on all issues with a search like https://github.com/jenkins-infra/helpdesk/issues?q=is%3Aissue+sort%3Acreated-desc+label%3Aimported-jira-issue
	- [x] Comment added to every INFRA jira issues:

		    ```
		    For your information, [all INFRA issues|https://issues.jenkins.io/projects/INFRA/issues/] related to the [Jenkins Infrastructure project|https://www.jenkins.io/projects/infrastructure/] have been transferred to Github: https://github.com/jenkins-infra/helpdesk/issues
		    
		    Here is the direct link to this issue in Github: https://github.com/jenkins-infra/helpdesk/issues/2677
		    And here is the link to a search for related issues: https://github.com/jenkins-infra/helpdesk/issues?q=is%3Aissue+sort%3Aupdated-desc+%22INFRA-3132%22
		    
		    (Note: this is an automated bulk comment)
		    ```

- [x] Remove the "Create" permission like what was done for HOSTING: https://github.com/jenkins-infra/helpdesk/issues/2729

- [x] Redirect interactions from Jira to this repository
	- [x] Notice with link to helpdesk in issue<b>s</b> wizzard

- [x] Communicate the switch from Jira issues to Github issues
	- [x] mailing lists
	- [x] irc
- [x] Update reference to Jira INFRA project: https://github.com/jenkins-infra/helpdesk/issues/2730

- [x] Publish importer and commenter scripts

## Command to subscribe to your issues

To subscribe in bulk to the issues where your `<username>` is mentioned you can use this snippet, courtesy of @timja:

```
gh issue list --search 'is:issue is:open <username>' --limit 500 --json id | jq -r '.[].id' | xargs -I{} gh api graphql -F subjectID={} -f query='mutation ($subjectID: ID!) {  updateSubscription(input: {subscribableId: $subjectID, state: SUBSCRIBED}) {    clientMutationId  }}'
```
(you'll need [`gh` cli](https://cli.github.com/) installed and configured)

Likely you will need the `notifications` scope added see below:
```
gh auth refresh --scopes write:org,read:public_key,notifications
```

Formated query:
```
mutation ($subjectID: ID!) {
  updateSubscription(input: {subscribableId: $subjectID, state: SUBSCRIBED}) {
    clientMutationId
  }
}
```

## Related Infrastructure Meeting notes

See https://github.com/jenkins-infra/documentation/blob/7e9001f28a05d564531cf47255dcfca1c9a7f487/meetings/2022-01-11.md?plain=1#L46-L69

**Comment by timja** [comment]
I've used this in the past to import them:
https://github.com/rantoniuk/jira-issues-importer

Example imported issue:
https://github.com/jenkinsci/azure-vm-agents-plugin/issues/198

The script itself doesn't touch Jira.
I used the bulk change feature in Jira to add a comment:

https://issues.jenkins.io/browse/JENKINS-64790?focusedCommentId=406904&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-406904

> All issues have been transferred to GitHub.
>
> See https://github.com/jenkinsci/azure-vm-agents-plugin/issues
>
> Search the issue title to find it.
>
> (This is a bulk comment and can't link to the specific issue)

Ideally it would give a direct link but that would mean needing to improve the script to update Jira as it creates them.

I tested it first on a fork repo.

**Comment by lemeurherve** [comment]
My initial research led me to https://github.com/dougwaldron/jira-issues-importer which works with XML exports.

Will look into https://github.com/rantoniuk/jira-issues-importer too, thanks for these links and information!

**Comment by timja** [comment]
It looks to just be another fork of something and possibly more up to date 😄

**Comment by lemeurherve** [comment]
Noted :)

**Comment by lemeurherve** [comment]
Thanks for the jira issue wizzard @timja!
![image](https://user-images.githubusercontent.com/91831478/149005943-6dc60a98-93f2-4558-b0b6-8ac2d3d6f7cd.png)

**Comment by lemeurherve** [comment]
I've made a little bash script to use [Jira REST API](https://developer.atlassian.com/server/jira/platform/jira-rest-api-examples/#adding-a-comment).
Unfortunatelly I've learned too late about its `notifyUsers=false` parameter 😓

**Comment by timja** [comment]
tbh worth notifying people I think otherwise they would be subscribed to the old issue which will not get any more updates.

(annoying for people subscribed to lots of issues but meh)

**Comment by lemeurherve** [comment]
Yes, it's planned, I just like to clean it a little bit before. (Same for my import script modifications)

**Comment by jglick** [comment]
> annoying for people subscribed to lots of issues

I just asked GMail to select everything from @lemeurherve on that day and bulk-delete. :grin:

**Comment by lemeurherve** [comment]
While @timja has opened a separate issue for the scripts/service for migrating issues from Jira to Github, here are the links to [my modified jira-importer](https://github.com/lemeurherve/jira-issues-importer), and to [my basic bulk jira commenter script](https://github.com/lemeurherve/jira-issues-importer/blob/master/jira-commenter.sh).
